### ISSUE TITLE
Сложная структура price

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [yuriipereverziev/Organic#7]
Может я чего-то не понимаю, но 
```
price: [
    {
        id: '01-1',
        newPrice: '20.00'
    },
    {
        id: '01-2',
        oldPrice: '25.00'
    },
],
```
Почему бы это, не заменить на это?
```
price: { 
  newPrice: '20.00'
  oldPrice: '25.00'
}
```
Мне кажется так проще работать с этими данными

**Comment by yuriipereverziev** [comment]
это тогда и получаеться второй уровень вложенности как было в задании ? я просто не совсем понял)
